// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: onlinestatus/onlinestatus.proto

package onlinestatuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserStatusRequest) Reset() {
	*x = UserStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusRequest) ProtoMessage() {}

func (x *UserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusRequest.ProtoReflect.Descriptor instead.
func (*UserStatusRequest) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{0}
}

func (x *UserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PartyMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
}

func (x *PartyMembersRequest) Reset() {
	*x = PartyMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartyMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMembersRequest) ProtoMessage() {}

func (x *PartyMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMembersRequest.ProtoReflect.Descriptor instead.
func (*PartyMembersRequest) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{2}
}

func (x *PartyMembersRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type PartyMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *PartyMembersResponse) Reset() {
	*x = PartyMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartyMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMembersResponse) ProtoMessage() {}

func (x *PartyMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMembersResponse.ProtoReflect.Descriptor instead.
func (*PartyMembersResponse) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{3}
}

func (x *PartyMembersResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type TripDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideType  *RideType `protobuf:"bytes,1,opt,name=ride_type,json=rideType,proto3" json:"ride_type,omitempty"`
	Latitude  float64   `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64   `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *TripDataRequest) Reset() {
	*x = TripDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDataRequest) ProtoMessage() {}

func (x *TripDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDataRequest.ProtoReflect.Descriptor instead.
func (*TripDataRequest) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{4}
}

func (x *TripDataRequest) GetRideType() *RideType {
	if x != nil {
		return x.RideType
	}
	return nil
}

func (x *TripDataRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TripDataRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RideType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId string `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RideId   string `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
}

func (x *RideType) Reset() {
	*x = RideType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideType) ProtoMessage() {}

func (x *RideType) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideType.ProtoReflect.Descriptor instead.
func (*RideType) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{5}
}

func (x *RideType) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RideType) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type TripSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance float64 `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Charge   float64 `protobuf:"fixed64,2,opt,name=charge,proto3" json:"charge,omitempty"`
	Time     float64 `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TripSummaryResponse) Reset() {
	*x = TripSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onlinestatus_onlinestatus_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripSummaryResponse) ProtoMessage() {}

func (x *TripSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onlinestatus_onlinestatus_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripSummaryResponse.ProtoReflect.Descriptor instead.
func (*TripSummaryResponse) Descriptor() ([]byte, []int) {
	return file_onlinestatus_onlinestatus_proto_rawDescGZIP(), []int{6}
}

func (x *TripSummaryResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripSummaryResponse) GetCharge() float64 {
	if x != nil {
		return x.Charge
	}
	return 0
}

func (x *TripSummaryResponse) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_onlinestatus_onlinestatus_proto protoreflect.FileDescriptor

var file_onlinestatus_onlinestatus_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f, 0x6f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2c, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x13,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x22, 0x30,
	0x0a, 0x14, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x22, 0x80, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x72, 0x69, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x08, 0x52, 0x69, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x69, 0x64, 0x65, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x13, 0x54, 0x72, 0x69, 0x70, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x32, 0x63, 0x0a, 0x0b, 0x54, 0x72, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x69, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1d, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x32, 0x69, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x32, 0x6a, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x79,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x74, 0x65, 0x2d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_onlinestatus_onlinestatus_proto_rawDescOnce sync.Once
	file_onlinestatus_onlinestatus_proto_rawDescData = file_onlinestatus_onlinestatus_proto_rawDesc
)

func file_onlinestatus_onlinestatus_proto_rawDescGZIP() []byte {
	file_onlinestatus_onlinestatus_proto_rawDescOnce.Do(func() {
		file_onlinestatus_onlinestatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_onlinestatus_onlinestatus_proto_rawDescData)
	})
	return file_onlinestatus_onlinestatus_proto_rawDescData
}

var file_onlinestatus_onlinestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_onlinestatus_onlinestatus_proto_goTypes = []interface{}{
	(*UserStatusRequest)(nil),    // 0: onlinestatus.UserStatusRequest
	(*UserStatusResponse)(nil),   // 1: onlinestatus.UserStatusResponse
	(*PartyMembersRequest)(nil),  // 2: onlinestatus.PartyMembersRequest
	(*PartyMembersResponse)(nil), // 3: onlinestatus.PartyMembersResponse
	(*TripDataRequest)(nil),      // 4: onlinestatus.TripDataRequest
	(*RideType)(nil),             // 5: onlinestatus.RideType
	(*TripSummaryResponse)(nil),  // 6: onlinestatus.TripSummaryResponse
}
var file_onlinestatus_onlinestatus_proto_depIdxs = []int32{
	5, // 0: onlinestatus.TripDataRequest.ride_type:type_name -> onlinestatus.RideType
	4, // 1: onlinestatus.TripService.SendTripData:input_type -> onlinestatus.TripDataRequest
	0, // 2: onlinestatus.UserStatusService.GetUserStatus:input_type -> onlinestatus.UserStatusRequest
	2, // 3: onlinestatus.PartyService.GetPartyMembers:input_type -> onlinestatus.PartyMembersRequest
	6, // 4: onlinestatus.TripService.SendTripData:output_type -> onlinestatus.TripSummaryResponse
	1, // 5: onlinestatus.UserStatusService.GetUserStatus:output_type -> onlinestatus.UserStatusResponse
	3, // 6: onlinestatus.PartyService.GetPartyMembers:output_type -> onlinestatus.PartyMembersResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_onlinestatus_onlinestatus_proto_init() }
func file_onlinestatus_onlinestatus_proto_init() {
	if File_onlinestatus_onlinestatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_onlinestatus_onlinestatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartyMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartyMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onlinestatus_onlinestatus_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_onlinestatus_onlinestatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_onlinestatus_onlinestatus_proto_goTypes,
		DependencyIndexes: file_onlinestatus_onlinestatus_proto_depIdxs,
		MessageInfos:      file_onlinestatus_onlinestatus_proto_msgTypes,
	}.Build()
	File_onlinestatus_onlinestatus_proto = out.File
	file_onlinestatus_onlinestatus_proto_rawDesc = nil
	file_onlinestatus_onlinestatus_proto_goTypes = nil
	file_onlinestatus_onlinestatus_proto_depIdxs = nil
}
